name: On Push

on:
  - push
  - pull_request

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: install-java
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: mvn-clean-package-site
        timeout-minutes: 1
        run: time mvn clean package site -B -e -X

#      - name: native-image
#        run: time ./cli-build.sh

      - name: code-coverage
        uses: codecov/codecov-action@v3

      - name: code-coverage-publish
        run: curl -s https://codecov.io/bash | bash

